version: 2.1
parameters:
  working-directory:
    type: string
    default: "~/keystone"

executors:
  node-executor:
    docker:
      - image: circleci/node:10.15
    working_directory: << pipeline.parameters.working-directory >>

commands:
  set-npm-auth:
    description: "Set NPM authentication"
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

  install-deps:
    description: "Install build dependencies"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-build-{{ checksum "yarn.lock" }}
      - run: yarn install --forzen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-build-{{ checksum "yarn.lock" }}

jobs:
  build:
     executor: node-executor
     steps:
       - checkout
       - install-deps
       - run: yarn build
       - persist_to_workspace:
          root: << pipeline.parameters.working-directory >>
          paths:
            - ./*
  publish:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - set-npm-auth
      - run: npm publish

workflows:
  version: 2.1
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
      - publish:
          context: twreporter
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
            branches:
              ignore: /.*/
